# Generated by Django 2.2.14 on 2020-12-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product2',
            new_name='medicine',
        ),
    ]
