# Generated by Django 3.1.2 on 2021-01-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201226_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.DeleteModel(
            name='medicine',
        ),
        migrations.AddField(
            model_name='product',
            name='shop_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
