# Generated by Django 3.1.2 on 2021-01-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210104_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='shop',
            name='pincode',
            field=models.IntegerField(default=700075),
        ),
    ]
