# Generated by Django 3.1.1 on 2021-01-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210113_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
